### ISSUE TITLE
Boot of KVMQM machines failing occasionally

### ISSUE THREAD

**Issue by jfornoff** [GLab/ToMaTo#1151]
Hi,

I've been running into some KVM machines failing to boot (multiple identical machines booting at the same time, most boot fine, some crash).

Screenshots of error output and host info attached.

Best regards,
Jan
![tomato_boot_failure](https://cloud.githubusercontent.com/assets/1319818/11559831/2e9eaf8c-99bc-11e5-9f9d-49bf7b7e9366.jpg)
![tomato_boot_failure_hostinfo](https://cloud.githubusercontent.com/assets/1319818/11559832/2e9fe208-99bc-11e5-833a-1436368e282c.jpg)

**Comment by dswd** [comment]
On inspection, the template was missing on the host, it was an empty file. The error message is consistent with that. So I think it is not because of the amount of nodes.
There is no apparent reason why the template is missing as the torrent file for it was present and downloading it via bittorrent succeeded. However, in that test run, the bittorrent client froze shortly after downloading the missing templates (needed to be killed -9). There might be a problem with the client, yet another reason for #1110.
The host has been fixed but we might want to include a way to detect this kind of problem before it surfaces.

**Comment by jfornoff** [comment]
Cool, sounds good!
It's not much of an issue to me personally, just wanted to make sure it's recorded over here.

Thanks for looking into it!
Regards,
Jan
