### ISSUE TITLE
Could not delete document (Element.topology refers to it)

### ISSUE THREAD

**Issue by dswd** [GLab/ToMaTo#1386]
Happened on backend_core

[View in Dump Manager](http://master.tomato-lab.org/dumpmanager/group/Exception__d31aca8c10a2d45d90288eb3573a9054)

Description:

```
{'type': 'OperationError', 'subject': 'Could not delete document (Element.topology refers to it)'}
```

Trace:

```
/code/service/tomato/topology.py, line 384, in timeout_task
 top.remove()

/code/service/tomato/generic.py, line 179, in remove
 self.action(self.REMOVE_ACTION, params)

/code/service/tomato/generic.py, line 166, in action
 return actn(self, **params)

/code/service/tomato/generic.py, line 24, in __call__
 return self.fn(obj, **kwargs)

/code/service/tomato/topology.py, line 239, in _remove
 self.delete()

/usr/local/lib/python2.7/dist-packages/mongoengine/document.py, line 500, in delete
 **self._object_key).delete(write_concern=write_concern, _from_doc_delete=True)

/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py, line 397, in delete
 raise OperationError(msg)
```

**Comment by t-gerhard** [comment]
We don't allow deleting topologies with elements. Topology._remove deletes elements before deleting the topology.
Why does this happen?

**Comment by t-gerhard** [comment]
Connection._remove() is the reason for this.

Connection._remove removes the reference from the elements to the connection. Then it tries to remove the elements, ignoring errors.
The elements' remove() function will not call Connection.remove() because they don't have the reference anymore. However, since the connection has not yet been deleted, Element.delete() will not work. The error is ignored when removing only a connection, but when trying to delete an Element simultaneously, this results in an error.

Solution should be: rewrite Connection._remove() so that it also removes the references from itself to its elements. I'll try this now.
